services:
    backend:
        build: ./
        container_name: arbitrage-backend
        ports:
            - "8000:8000"
        environment:
            - WALLEX_API_KEY=${WALLEX_API_KEY}
            - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
            - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/arbitrage
        depends_on:
            - db
            - prometheus

    db:
        image: postgres:15
        container_name: arbitrage-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: arbitrage
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - "9090:9090"

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
          - "3000:3000"
      environment:
          - GF_SECURITY_ADMIN_USER=admin
          - GF_SECURITY_ADMIN_PASSWORD=admin
          - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      volumes:
          - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
          - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
          - ./grafana/dashboards:/var/lib/grafana/dashboards
      depends_on:
          - prometheus

    postgres_exporter:
        image: prometheuscommunity/postgres-exporter:latest
        container_name: postgres_exporter
        restart: always
        environment:
            DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/arbitrage?sslmode=disable"
        ports:
            - "9187:9187"
        depends_on:
            - db

volumes:
    postgres_data:
    grafana_data:
