global:
  scrape_interval:     20s 
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'prometheus'
    scrape_interval: 20s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]
