{
 "title": "arbitrage",
 "time": { "from": "2025-10-24T11:33:32.420Z", "to": "2025-10-24T11:43:32.420Z" },
 "panels": [
  {
   "title": "Last Price Diff",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "TMN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_price_difference", "legendFormat": "{{currency}}" }
   ]
  },
  {
   "title": "Arbitrage Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_replace(\r\n  increase(arbitrage_opportunities_total[1m]) ,\r\n  \"display\",\r\n  \"Opportunities per 1 min\",\r\n  \"\",\r\n  \"\"\r\n)\r\n",
     "legendFormat": "{{display}}"
    }
   ]
  },
  {
   "title": "Success/Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "label_replace(increase(nobitex_success_total[5m]), \"exchange\", \"Nobitex Success\", \"\", \"\")\r\n",
     "legendFormat": "{{exchange}}"
    },
    {
     "expr": "label_replace(increase(nobitex_failure_total[5m]), \"exchange\", \"Nobitex Failure\", \"\", \"\")\r\n",
     "legendFormat": "{{exchange}}"
    },
    {
     "expr": "label_replace(increase(wallex_success_total[5m]), \"exchange\", \"Wallex Success\", \"\", \"\")\r\n",
     "legendFormat": "{{exchange}}"
    },
    {
     "expr": "label_replace(increase(wallex_failure_total[5m]), \"exchange\", \"Wallex Failure\", \"\", \"\")\r\n",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Exchange Response Time (Mean + Percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace( rate(nobitex_response_seconds_sum[5m]) / rate(nobitex_response_seconds_count[5m]), \"exchange\", \"Nobitex Mean\", \"\", \"\" )",
     "legendFormat": "{{exchange}}"
    },
    {
     "expr": "label_replace(\r\n  histogram_quantile(0.9, sum(rate(nobitex_response_seconds_bucket[5m])) by (le)),\r\n  \"exchange\", \"Nobitex P90\", \"\", \"\"\r\n)\r\n",
     "legendFormat": "{{exchange}}"
    },
    {
     "expr": "label_replace(\r\nrate(wallex_response_seconds_sum[5m]) / rate(wallex_response_seconds_count[5m]),\r\n\"exchange\", \"Wallex Mean\", \"\", \"\"\r\n)",
     "legendFormat": "{{exchange}}"
    },
    {
     "expr": "label_replace(\r\n  histogram_quantile(0.9, sum(rate(wallex_response_seconds_bucket[5m])) by (le)),\r\n  \"exchange\", \"Wallex P90\", \"\", \"\"\r\n)\r\n",
     "legendFormat": "{{exchange}}"
    }
   ]
  }
 ]
}